
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 38;
  public static final int right_parenthesis = 4;
  public static final int percent = 39;
  public static final int comma = 7;
  public static final int multiplication_sign = 37;
  public static final int constfloat = 41;
  public static final int more_than = 31;
  public static final int until = 14;
  public static final int addition_sign = 35;
  public static final int left_parenthesis = 3;
  public static final int struct = 13;
  public static final int less_than = 32;
  public static final int while_token = 15;
  public static final int more_than_equa_lto = 23;
  public static final int iden = 34;
  public static final int equal = 11;
  public static final int less_than_equal_to = 22;
  public static final int do_token = 25;
  public static final int EOF = 0;
  public static final int float_token = 10;
  public static final int ident = 2;
  public static final int right_bracket = 6;
  public static final int substraction_sign = 36;
  public static final int error = 1;
  public static final int double_equal = 24;
  public static final int or = 27;
  public static final int colon = 28;
  public static final int else_token = 16;
  public static final int void_token = 8;
  public static final int comment = 18;
  public static final int constint = 40;
  public static final int for_token = 20;
  public static final int if_token = 26;
  public static final int and = 19;
  public static final int not = 21;
  public static final int then_token = 17;
  public static final int constlit = 42;
  public static final int semicolon = 12;
  public static final int left_bracket = 5;
  public static final int right_squarebracket = 29;
  public static final int left_squarebracket = 30;
  public static final int dot = 33;
  public static final int int_token = 9;
  public static final int return_token = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ident",
  "left_parenthesis",
  "right_parenthesis",
  "left_bracket",
  "right_bracket",
  "comma",
  "void_token",
  "int_token",
  "float_token",
  "equal",
  "semicolon",
  "struct",
  "until",
  "while_token",
  "else_token",
  "then_token",
  "comment",
  "and",
  "for_token",
  "not",
  "less_than_equal_to",
  "more_than_equa_lto",
  "double_equal",
  "do_token",
  "if_token",
  "or",
  "colon",
  "right_squarebracket",
  "left_squarebracket",
  "more_than",
  "less_than",
  "dot",
  "iden",
  "addition_sign",
  "substraction_sign",
  "multiplication_sign",
  "slash",
  "percent",
  "constint",
  "constfloat",
  "constlit",
  "return_token"
  };
}

