
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int percent = 11;
  public static final int float_token = 18;
  public static final int constfloat = 13;
  public static final int substraction_sign = 8;
  public static final int addition_sign = 7;
  public static final int right_bracket = 6;
  public static final int multiplication_sign = 9;
  public static final int right_parenthesis = 4;
  public static final int left_bracket = 5;
  public static final int semicolon = 20;
  public static final int return_token = 15;
  public static final int constlit = 14;
  public static final int ident = 2;
  public static final int EOF = 0;
  public static final int constint = 12;
  public static final int void_token = 16;
  public static final int equal = 21;
  public static final int slash = 10;
  public static final int error = 1;
  public static final int left_parenthesis = 3;
  public static final int int_token = 17;
  public static final int comma = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ident",
  "left_parenthesis",
  "right_parenthesis",
  "left_bracket",
  "right_bracket",
  "addition_sign",
  "substraction_sign",
  "multiplication_sign",
  "slash",
  "percent",
  "constint",
  "constfloat",
  "constlit",
  "return_token",
  "void_token",
  "int_token",
  "float_token",
  "comma",
  "semicolon",
  "equal"
  };
}

